### PR TITLE
Fix typo error

### PR DESCRIPTION
**Pull request by theodorosploumis**
By the way, is this **project active**? I am making a list with Drupal Development tools and this is one of these.

### CODE REVIEW

**Comment by dergachev** [comment]
Thanks for catching the spelling error! At Evolving Web we've switched over to docker for most things, but will still fix bugs if people report them (for now) in this issue. Cheers,

**Comment by theodorosploumis** [comment]
In fact it needs a lot of things to be fixed (such as chef cookbook updates) so better move on for now.

**Comment by dergachev** [comment]
OK good to know, thanks so much for testing it out!

And in general you're doing a very good thing by collating all the drupal VMs at http://goo.gl/ucwWdt .
I wish I had such a list when I started looking at alternatives. :)

**Comment by dergachev** [comment]
Also should note that the frequency with which contrib chef cookbooks broke (either due to bugs or backwards incompatible changes) was one of the reason we moved away from Chef.

**Comment by theodorosploumis** [comment]
Agree! Chef is a mess as also Puppet... Ansible is far better but Docker is the future.

**Pull request merged**
